### ISSUE TITLE
ip: consolidate ipv4 & ipv6 addrs into one column?

### ISSUE THREAD

**Issue by ryran** [ryran/xsos#199]
E.g., something like this:

```
IP
  Interface      Master IF  MAC Address        MTU     State  IP Address
  =========      =========  =================  ======  =====  ============================================================
  lo             -          -                  65536   up     ::1/128 (host)
                                                              127.0.0.1/8
  enp0s25        -          54:ee:75:4b:d5:bd  1500    up     -
  wlp4s0         -          34:02:86:20:aa:85  1500    DOWN   -
  virbr0         -          52:54:00:c8:03:27  1500    up     192.168.122.1/24
  virbr0-nic     virbr0     52:54:00:c8:03:27  1500    DOWN   -
  enp0s20u3u1u3  -          00:50:b6:7f:22:44  1500    up     ⣿⣿⣿⣿:⣿⣿⣿⣿:⣿⣿⣿⣿:⣿⣿⣿⣿:⣿⣿⣿⣿:⣿⣿⣿⣿:⣿⣿⣿⣿:⣿⣿⣿⣿/⣿⣿⣿ (global)
                                                              ⣿⣿⣿⣿:⣿⣿⣿⣿:⣿⣿⣿⣿:⣿⣿⣿⣿:⣿⣿⣿⣿:⣿⣿⣿⣿:⣿⣿⣿⣿:⣿⣿⣿⣿/⣿⣿⣿ (link)
                                                              ⣿⣿⣿.⣿⣿⣿.⣿⣿⣿.⣿⣿⣿/⣿⣿
```

Request for comment.

**Comment by jbainbri** [comment]
I'm gonna say no, because I often copy-paste these and IPv6 adoption is currently so low, I'll be snipping out the IPv6 addresses for brevity more often than not.

If you do merge them, then please place IPv4 first, so IPv6 can be removed by deleting lines after the line with the interface name.

eg, IPv4 first:

~~~
IP
  Interface      Master IF  MAC Address        MTU     State  IP Address
  =========      =========  =================  ======  =====  ==============
  lo             -          -                  65536   up     127.0.0.1/8
                                                              ::1/128 (host)
~~~

is preferable to IPv6 first:

~~~
IP
  Interface      Master IF  MAC Address        MTU     State  IP Address
  =========      =========  =================  ======  =====  ==============
  lo             -          -                  65536   up     ::1/128 (host)
                                                              127.0.0.1/8
~~~

**Comment by daVikes** [comment]
I think as long as you can grep for tcpv4 or tcpv6 that would be good or has that be an output parameter.

**Comment by artgenos** [comment]
my issue is only while reading a sosreport can you get both ipv4 and ipv6 with one command. just running xsos you need to run it once with -i and once with -6. running it with -i6 only shows ipv6. also --net only shows ipv4 running without sosreport. unless i am missing something easy.

**Comment by ryran** [comment]
> my issue is only while reading a sosreport can you get both ipv4 and ipv6 with one command. just running xsos you need to run it once with -i and once with -6. running it with -i6 only shows ipv6. also --net only shows ipv4 running without sosreport. unless i am missing something easy.

Indeed. That was a mistake on my part with the latest commit. I meant to only show both when using `--all` but I also accidentally enabled for whenever running against a sosreport.

I'll fix it soon so that `--net` always does both.

**Comment by superjamie** [comment]
After using this for a while, I can confirm I prefer v4 and v6 separated. I think we can close this off.

**Comment by ryran** [comment]
I like the fanciness and future-proofness of having them integrated, but I'll defer to the users here.
