### ISSUE TITLE
--help, -h, and -? don't display any options

### ISSUE THREAD

**Issue by billq** [ryran/xsos#208]
The control characters used in the HELP_OPTS_CONTENT, HELP_OPTS_DISPLAY, and HELP_OPTS_SPECIAL are preventing the echo from displaying the contents.

[xsos_diff.txt](https://github.com/ryran/xsos/files/485625/xsos_diff.txt)

**Comment by ryran** [comment]
@billq
Hi Bill. If there's a problem with the help pages for you, then there's likely similar problems elsewhere as that character is used all throughout xsos as a column separator.

The character in question ([❚](http://graphemica.com/%E2%9D%9A)) is a multi-byte character, so that's what's different ... as to why that's a problem for you and no one else ever in the history of xsos users ... I can't say. What OS & version are you using? What architecture?

**Comment by billq** [comment]
Hi Ryan,

Good questions, all.  A co-worker and I tried it on RHEL6.7 and RHEL7.2
using two different logins.  It may very well be something funky with our
environment - difficult to sanitize that here as all servers are built
pretty much the same.  Any particular reason to use a multibyte char as a
column separator?  I generally stay away from non-ASCII in scripts, but
maybe thats just me:)

Great tool, BTW.  Very handy!

Bill

**Comment by billq** [comment]
One of my brilliant co-workers was quick to point out that the script
doesn't support the posix locale...  We use LC_ALL=C setting
LC_ALL=en_US.UTF-8 provides expected output.  Perhaps setting the locale in
the script is the easiest fix?

**Comment by ryran** [comment]
Long-term we could probably get better performance by making it possible to run in `C` locale, but for now I've just forced UTF-8 in the script itself.
