### ISSUE TITLE
Virtually all modules break when sosreport root dir has spaces in it

### ISSUE THREAD

**Issue by ryran** [ryran/xsos#69]
```
[rsaw:sos]$ ll -d ram-4\ asdf/
drwxr-xr-x. 16 rsaw rsaw 4096 Aug 18 08:00 ram-4 asdf/
[rsaw:sos]$ xsos -a ram-4\ asdf/
Warning: 'ram-4/dmidecode' file unreadable; skipping bios check

Warning: 'ram-4/proc/' file unreadable; skipping os check

Warning: 'ram-4/proc/cpuinfo' file unreadable; skipping cpu check

Warning: 'ram-4/proc/meminfo' file unreadable; skipping mem check

Warning: 'ram-4/proc/partitions' file unreadable; skipping disks check

Warning: 'ram-4/sos_commands/devicemapper/multipath_-v4_-ll' file unreadable; skipping mpath check

Warning: 'ram-4/lspci' file unreadable; skipping lspci check

Warning: 'ram-4/sos_commands/networking/ethtool*' file unreadable; skipping ethtool check

Warning: 'ram-4/sos_commands/networking/ip_address' file unreadable; skipping ip check

Warning: 'ram-4/proc/net/' file unreadable; skipping net check

Warning: 'ram-4/proc/sys/' file unreadable; skipping sysctl check

Warning: 'ram-4/ps' file unreadable; skipping ps check

[rsaw:sos]$ cd ram-4\ asdf/
[rsaw:ram-4 asdf]$ xsos -a . >/dev/null
[rsaw:ram-4 asdf]$ 
```

**Comment by lathan** [comment]
It looks like this is a limitation with `getopt`. Maybe the bash built-in `getopts` can handle this better. [This guy](http://aplawrence.com/Unix/getopts.html) has something to say about it, but I only had time to look briefly today.

What happens in our specific case is the following.

```
PARSE $(getopt -u --name=$pzero -o $sopts -l $lopts -- "$@")
```
When `getopt` parses the command line parameters above, even though `"$@"` is given with double quotes which would prevent splitting, getopt splits the result on spaces anyway. As a result, when at the end of the PARSE function we do `sosroot=$1` the `$1` is produced by `getopt` and is the first part of the split argument.

A workaround for xsos would be to do `sosroot="$@"`. This would mean that everything after `--` is taken literally as the path for the sosreport. This is a workaround because it should not be necessary. For example, if xsos needed to accept multiple arguments (which will probably never be the case), just like `rm` does.

Sorry if this comment is a bit unstructured, I just wanted to make a quick note so I don't forget.

**Comment by ryran** [comment]
Good call on figuring this out @lathan ... your simple fix of `sosroot=$@` makes it possible to deal with spaces in sosroot.

Unfortunately you've highlighted a wider problem with `getopt` that I hadn't noticed ... I can't for the life of me figure out a way to fix this. To be clear, this still affects any options that accept multi-word arguments, e.g., `--B` or `--C`. Oh well.

PS: Equally unfortunate is how horrible bash's built-in `getopt` is. It can't even do double-dash options. I guess this will just have to wait for the core-rewrite in python.

**Comment by lathan** [comment]
Thnx for pushing the workaround.
Still, I have a suspicion that I might be missing something. I'm looking another bash program I'm familiar with to see how it's done there.

**Comment by lathan** [comment]
Also, the reference implementation [here](https://git.kernel.org/cgit/utils/util-linux/util-linux.git/tree/misc-utils/getopt-parse.bash#n16) doesn't seem to have this problem.
